version: "3.9"

services:
  api:
    container_name: api
    profiles: ["api"]
    restart: always
    environment:
      ENVIRONMENT: ${ENVIRONMENT:-development}
      PORT: ${PORT:-3000}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE: ${DATABASE}
      LOG_LEVEL: ${LOG_LEVEL:-info}
      DOMAIN_NAME: ${DOMAIN_NAME}
      JWT_DURATION: ${JWT_DURATION}
      JWT_SECRET: ${JWT_SECRET}
      GEOIP_API_KEY: ${GEOIP_API_KEY}
      GEOIP_ENDPOINT: ${GEOIP_ENDPOINT}
      CACHE_PASSWORD: ${CACHE_PASSWORD}
      CACHE_HOST: ${CACHE_HOST}
      JAEGER_HOST: ${JAEGER_HOST}
      DEBUG_ENABLED: ${DEBUG_ENABLED:-false}
    build:
      target: development
      context: .
      args:
        - GOLANG_VERSION=1.22.4
        - ALPINE_VERSION=3.20
    ports:
      - "3000:3000"
    links:
      - db
      - redis
      - jaeger
    networks:
      - api

  db:
    container_name: postgres
    image: postgis/postgis:16-3.4
    platform: linux/amd64
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE}
#      TODO add all env vars into here
    volumes:
      - source: database
        target: /var/lib/postgresql/data
        type: volume
    ports:
      - "5432:5432"
    networks:
      - api

  redis:
    container_name: redis
    image: redis:7.2.5
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - cache:/data
    networks:
      - api
    entrypoint: redis-server --appendonly yes --requirepass ${CACHE_PASSWORD}

  jaeger:
    container_name: jaeger
    image: "jaegertracing/all-in-one:latest"
    restart: always
    ports:
      - "16686:16686"
      - "14268:14268"
    networks:
      - api

# TODO adminer

volumes:
  database: {}
  cache: {}

networks:
  api:
    driver: bridge
    internal: false
