version: "3.9"

services:
  api:
    container_name: api
    restart: always
    env_file: development.env
    environment:
      PORT: ${PORT}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE: ${DATABASE}
    build:
      target: development
      context: .
      args:
        - GOLANG_VERSION=1.22.4
        - ALPINE_VERSION=3.20
    ports:
      - "3000:3000"
    links:
      - db
    networks:
      - api

  db:
    container_name: postgres
    image: postgres:16.3
    restart: always
    env_file: development.env
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE}
    volumes:
      - source: database
        target: /var/lib/postgresql/data
        type: volume
    ports:
      - "5432:5432"
    networks:
      - api

# TODO adminer

volumes:
  database: {}

networks:
  api:
    driver: bridge
    internal: false
