// Code generated by mockery v2.43.2. DO NOT EDIT.

package mockservice

import (
	context "context"

	muzz "github.com/nickbadlose/muzz"
	mock "github.com/stretchr/testify/mock"
)

// AuthRepository is an autogenerated mock type for the AuthRepository type
type AuthRepository struct {
	mock.Mock
}

type AuthRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *AuthRepository) EXPECT() *AuthRepository_Expecter {
	return &AuthRepository_Expecter{mock: &_m.Mock}
}

// UserByEmail provides a mock function with given fields: ctx, email
func (_m *AuthRepository) UserByEmail(ctx context.Context, email string) (*muzz.User, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for UserByEmail")
	}

	var r0 *muzz.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*muzz.User, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *muzz.User); ok {
		r0 = rf(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*muzz.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AuthRepository_UserByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UserByEmail'
type AuthRepository_UserByEmail_Call struct {
	*mock.Call
}

// UserByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *AuthRepository_Expecter) UserByEmail(ctx interface{}, email interface{}) *AuthRepository_UserByEmail_Call {
	return &AuthRepository_UserByEmail_Call{Call: _e.mock.On("UserByEmail", ctx, email)}
}

func (_c *AuthRepository_UserByEmail_Call) Run(run func(ctx context.Context, email string)) *AuthRepository_UserByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *AuthRepository_UserByEmail_Call) Return(_a0 *muzz.User, _a1 error) *AuthRepository_UserByEmail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AuthRepository_UserByEmail_Call) RunAndReturn(run func(context.Context, string) (*muzz.User, error)) *AuthRepository_UserByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// NewAuthRepository creates a new instance of AuthRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthRepository {
	mock := &AuthRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
